### ISSUE TITLE
Wine score range or baseline (e.g. between 90 and 92 points)

### ISSUE THREAD

**Issue by Neri-hV** [alfredodeza/mapping-data#4]
Hello Alfredo, 
Thanks for the previous answer and the changes that you did it in the exercise jupyter notebook.  
I did this:
https://github.com/Neri-hV/mapping-data/blob/main/exercise_modified.ipynb

However, I still need some help.  Could you please share with us a resource to learn how to find information and also filter the data in a dictionary of many lists in python (I couldn't find any on google who allow me to obtain a range of values).
Maybe this topic is some pre-knowledge that you assume that we have because  in the exercises and videos you only explain a simple dictionary with one list.

**Comment by alfredodeza** [comment]
Hi @Neri-hV , thanks again for bringing up some of the challenges. Using Pandas will make this easier, but I didn't cover Pandas in this course (although it is part of the specialization). Looping over a list of dictionaries is the same as other loops with the added complexity that each item is a dictionary. I've updated the Jupyter Notebook to give an extra example on how to do that and updated the file opening to ignore any potential encoding errors. Here is part of the snippet:

```python
# This example creates a new list that only has wines from Napa Valley. The new list is called napa_wines:
napa_wines = []
for wine in wines:
    if 'Napa' in wine['region']:
        napa_wines.append(wine)

napa_wines
```

That should get you all the way. Otherwise, feel free to re-open this issue or create a new one
